### ISSUE TITLE
Error opening file: hg19_mm10_transgenes.rRNA.intervals

### ISSUE THREAD

**Issue by olechnwin** [Hoohm/dropSeqPipe#24]
Hi,

I have another error:
xception in thread "main" htsjdk.samtools.SAMException: Error opening file: /opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals

This seems to be a new feature of Drop-seq 1.13. Can you please let me know how to fix this? Also, what does this do?

Thanks!

**Comment by Hoohm** [comment]
Could you please provide more context. I don't see where the error comes from.

Which step is this?
Are you using the reference of the McCarroll lab or did you make your own?

**Comment by olechnwin** [comment]
Sorry here it is. Hard for me to tell since I'm doing multi core, but I am guessing it's the singleCellRnaSeqMetricsCollector? The rRNA.intervals file was never created. I am using the reference of the McCarroll lab. 
```

+ java -Xmx32g -Djava.io.tmpdir=/tmp -jar /opt/Drop-seq_tools-1.13/jar/dropseq.jar DigitalExpression I=data/sample1_N706_S2_L001_MOUSE_unfiltered.bam O=summary/sample1_N706_S2_L001_MOUSE_umi_expression_matrix.txt MIN_BC_READ_THRESHOLD=1 CELL_BC_FILE=summary/sample1_N706_S2_L001_MOUSE_barcodes.csv
+ java -Xmx32g -Djava.io.tmpdir=/tmp -jar /opt/Drop-seq_tools-1.13/jar/dropseq.jar GatherMolecularBarcodeDistributionByGene I=data/sample1_N706_S2_L001_MOUSE_unfiltered.bam O=logs/sample1_N706_S2_L001_MOUSE_umi_per_gene.tsv CELL_BC_FILE=summary/sample1_N706_S2_L001_MOUSE_barcodes.csv
+ java -Xmx32g -Djava.io.tmpdir=/tmp -jar /opt/Drop-seq_tools-1.13/jar/dropseq.jar GatherMolecularBarcodeDistributionByGene I=data/sample1_N706_S2_L001_HUMAN_unfiltered.bam O=logs/sample1_N706_S2_L001_HUMAN_umi_per_gene.tsv CELL_BC_FILE=summary/sample1_N706_S2_L001_HUMAN_barcodes.csv
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector INPUT=data/sample1_N706_S2_L001_MOUSE_unfiltered.bam OUTPUT=logs/samplel1_N706_S2_L001_MOUSE_rna_metrics.txt ANNOTATIONS_FILE=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.refFlat RIBOSOMAL_INTERVALS=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals CELL_BC_FILE=summary/sample1_N706_S2_L001_MOUSE_barcodes.csv    CELL_BARCODE_TAG=XC STRAND_SPECIFICITY=NONE RRNA_FRAGMENT_PERCENTAGE=0.8 READ_MQ=10 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.DigitalExpression OUTPUT_READS_INSTEAD=true OUTPUT=summary/sample1_N706_S2_L001_MOUSE_counts_expression_matrix.txt INPUT=data/samplel1_N706_S2_L001_MOUSE_unfiltered.bam CELL_BC_FILE=summary/sample1_N706_S2_L001_MOUSE_barcodes.csv    CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.DigitalExpression OUTPUT=summary/sample1_N706_S2_L001_MOUSE_umi_expression_matrix.txt INPUT=data/sample1_N706_S2_L001_MOUSE_unfiltered.bam MIN_BC_READ_THRESHOLD=1 CELL_BC_FILE=summary/sample1_N706_S2_L001_MOUSE_barcodes.csv    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS EDIT_DISTANCE=1 READ_MQ=10 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
INFO	2018-03-14 14:36:48	SingleCellRnaSeqMetricsCollector	Found 334 cell barcodes in file
INFO	2018-03-14 14:36:48	BarcodeListRetrieval	Found 334 cell barcodes in file
INFO	2018-03-14 14:36:48	DigitalExpression	Calculating digital expression for [334] cells.
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.DigitalExpression OUTPUT_READS_INSTEAD=true OUTPUT=summary/sample1_N706_S2_L001_HUMAN_counts_expression_matrix.txt INPUT=data/samplel1_N706_S2_L001_HUMAN_unfiltered.bam CELL_BC_FILE=summary/sample1_N706_S2_L001_HUMAN_barcodes.csv    CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector INPUT=data/samplel1_N706_S2_L001_HUMAN_unfiltered.bam OUTPUT=logs/sample1_N706_S2_L001_HUMAN_rna_metrics.txt ANNOTATIONS_FILE=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.refFlat RIBOSOMAL_INTERVALS=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals CELL_BC_FILE=summary/sample1_N706_S2_L001_HUMAN_barcodes.csv    CELL_BARCODE_TAG=XC STRAND_SPECIFICITY=NONE RRNA_FRAGMENT_PERCENTAGE=0.8 READ_MQ=10 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.DigitalExpression OUTPUT=summary/samplel1_N706_S2_L001_HUMAN_umi_expression_matrix.txt INPUT=data/sample1_N706_S2_L001_HUMAN_unfiltered.bam MIN_BC_READ_THRESHOLD=1 CELL_BC_FILE=summary/sample1_N706_S2_L001_HUMAN_barcodes.csv    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS EDIT_DISTANCE=1 READ_MQ=10 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
INFO	2018-03-14 14:36:48	BarcodeListRetrieval	Found 334 cell barcodes in file
INFO	2018-03-14 14:36:48	DigitalExpression	Calculating digital expression for [334] cells.
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.GatherMolecularBarcodeDistributionByGene OUTPUT=logs/sample1_N706_S2_L001_MOUSE_umi_per_gene.tsv INPUT=data/sample1_N706_S2_L001_MOUSE_unfiltered.bam CELL_BC_FILE=summary/sample1_N706_S2_L001_MOUSE_barcodes.csv    CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
[Wed Mar 14 14:36:48 EDT 2018] org.broadinstitute.dropseqrna.barnyard.GatherMolecularBarcodeDistributionByGene OUTPUT=logs/sample1_N706_S2_L001_HUMAN_umi_per_gene.tsv INPUT=data/sample1_N706_S2_L001_HUMAN_unfiltered.bam CELL_BC_FILE=summary/sample1_N706_S2_L001_HUMAN_barcodes.csv    CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Mar 14 14:36:48 EDT 2018] Executing as cxx@himem01.cluster on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
INFO	2018-03-14 14:36:48	BarcodeListRetrieval	Found 141 cell barcodes in file
INFO	2018-03-14 14:36:48	DigitalExpression	Calculating digital expression for [141] cells.
INFO	2018-03-14 14:36:48	SingleCellRnaSeqMetricsCollector	Found 141 cell barcodes in file
INFO	2018-03-14 14:36:48	BarcodeListRetrieval	Found 141 cell barcodes in file
INFO	2018-03-14 14:36:48	DigitalExpression	Calculating digital expression for [141] cells.
INFO	2018-03-14 14:36:48	BarcodeListRetrieval	Found 334 cell barcodes in file
INFO	2018-03-14 14:36:48	BarcodeListRetrieval	Found 141 cell barcodes in file
INFO	2018-03-14 14:36:49	FilterBAM	Processed    12,000,000 records.  Elapsed time: 00:00:47s.  Time for last 1,000,000:    1s.  Last read position: */*
INFO	2018-03-14 14:36:52	FilterBAM	Processed     6,000,000 records.  Elapsed time: 00:00:49s.  Time for last 1,000,000:   12s.  Last read position: MOUSE_2:122,011,881
INFO	2018-03-14 14:36:53	FilterBAM	Processed    13,000,000 records.  Elapsed time: 00:00:51s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2018-03-14 14:36:54	SingleCellRnaSeqMetricsCollector	Loaded 94207 genes.
[Wed Mar 14 14:36:54 EDT 2018] org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector done. Elapsed time: 0.10 minutes.
Runtime.totalMemory()=2595749888
Exception in thread "main" htsjdk.samtools.SAMException: Error opening file: /opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals
	at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:529)
	at htsjdk.samtools.util.IOUtil.openFileForBufferedReading(IOUtil.java:786)
	at htsjdk.samtools.util.IntervalList.fromPath(IntervalList.java:408)
	at htsjdk.samtools.util.IntervalList.fromFile(IntervalList.java:399)
	at picard.analysis.directed.RnaSeqMetricsCollector.makeOverlapDetector(RnaSeqMetricsCollector.java:69)
	at org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector$CollectorFactory.<init>(SingleCellRnaSeqMetricsCollector.java:253)
	at org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector.getRNASeqMetricsCollector(SingleCellRnaSeqMetricsCollector.java:169)
	at org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector.doWork(SingleCellRnaSeqMetricsCollector.java:135)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
Caused by: java.nio.file.NoSuchFileException: /opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:525)
	... 10 more
INFO	2018-03-14 14:36:54	SingleCellRnaSeqMetricsCollector	Loaded 94207 genes.
[Wed Mar 14 14:36:54 EDT 2018] org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector done. Elapsed time: 0.10 minutes.
Runtime.totalMemory()=2595749888
Exception in thread "main" htsjdk.samtools.SAMException: Error opening file: /opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals
	at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:529)
	at htsjdk.samtools.util.IOUtil.openFileForBufferedReading(IOUtil.java:786)
	at htsjdk.samtools.util.IntervalList.fromPath(IntervalList.java:408)
	at htsjdk.samtools.util.IntervalList.fromFile(IntervalList.java:399)
	at picard.analysis.directed.RnaSeqMetricsCollector.makeOverlapDetector(RnaSeqMetricsCollector.java:69)
	at org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector$CollectorFactory.<init>(SingleCellRnaSeqMetricsCollector.java:253)
	at org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector.getRNASeqMetricsCollector(SingleCellRnaSeqMetricsCollector.java:169)
	at org.broadinstitute.dropseqrna.barnyard.SingleCellRnaSeqMetricsCollector.doWork(SingleCellRnaSeqMetricsCollector.java:135)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
Caused by: java.nio.file.NoSuchFileException: /opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:525)
	... 10 more
Error in rule SingleCellRnaSeqMetricsCollector_whitelist_species:
    jobid: 27
    output: logs/sample1_N706_S2_L001_MOUSE_rna_metrics.txt

Error in rule SingleCellRnaSeqMetricsCollector_whitelist_species:
    jobid: 30
    output: logs/sample1_N706_S2_L001_HUMAN_rna_metrics.txt

RuleException:
CalledProcessError in line 66 of /opt/dropSeqPipe/rules/extract_expression_species.smk:
Command ' set -euo pipefail;  /opt/Drop-seq_tools-1.13/drop-seq-tools-wrapper.sh -t ~/tmp -m 32g -p SingleCellRnaSeqMetricsCollector		INPUT=data/sample1_N706_S2_L001_MOUSE_unfiltered.bam		OUTPUT=logs/sample1_N706_S2_L001_MOUSE_rna_metrics.txt		ANNOTATIONS_FILE=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.refFlat		CELL_BC_FILE=summary/sample1_N706_S2_L001_MOUSE_barcodes.csv		RIBOSOMAL_INTERVALS=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals ' returned non-zero exit status 1.
  File "/opt/dropSeqPipe/rules/extract_expression_species.smk", line 66, in __rule_SingleCellRnaSeqMetricsCollector_whitelist_species
  File "opt/miniconda3/envs/dropSeqPipe/lib/python3.6/concurrent/futures/thread.py", line 56, in run
RuleException:
CalledProcessError in line 66 of /opt/dropSeqPipe/rules/extract_expression_species.smk:
Command ' set -euo pipefail;  /opt/Drop-seq_tools-1.13/drop-seq-tools-wrapper.sh -t ~/tmp -m 32g -p SingleCellRnaSeqMetricsCollector		INPUT=data/sample1_N706_S2_L001_HUMAN_unfiltered.bam		OUTPUT=logs/sample1_N706_S2_L001_HUMAN_rna_metrics.txt		ANNOTATIONS_FILE=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.refFlat		CELL_BC_FILE=summary/sample1_N706_S2_L001_HUMAN_barcodes.csv		RIBOSOMAL_INTERVALS=/opt/dropSeqPipe/ref/hg19_mm10_transgenes.rRNA.intervals ' returned non-zero exit status 1.
  File "/opt/dropSeqPipe/rules/extract_expression_species.smk", line 66, in __rule_SingleCellRnaSeqMetricsCollector_whitelist_species
  File "/opt/miniconda3/envs/dropSeqPipe/lib/python3.6/concurrent/futures/thread.py", line 56, in run
[Wed Mar 14 14:36:54 EDT 2018] org.broadinstitute.dropseqrna.utils.FilterBAM done. Elapsed time: 0.87 minutes.
Runtime.totalMemory()=2611478528
Finished job 24.
6 of 36 steps (17%) done


```

**Comment by Hoohm** [comment]
Yes, that is the problem is here: https://github.com/Hoohm/dropSeqPipe/blob/1fe59178579ec373c5224001d0faf9ce055c5308/rules/extract_expression_species.smk#L60

This should be in input instead of params so that it would create it.
What you can do is simply run `meta` once and it will create it. It will run after that.

This is fixed in the next version.

**Comment by olechnwin** [comment]
Sorry. can you please clarify? What does that mean to run meta?
Never mind. Got it. Going to run it now.

**Comment by Hoohm** [comment]
Sure.
When you run the pipeline you can run different steps separately.
so running: `snakemake meta` will run the meta data creation as one thing. This will create the missing files you need.

**Comment by olechnwin** [comment]
Thank you for all your help. That fix the error. Closing this issue.

**Comment by Jun-Lizst** [comment]
I continue to encounter this problem. please give some suggestion:
u2510@GenekServer-0:~/ncbi/public/sra/dropSeqPipe-0.31$ snakemake --cores 8 extract --use-conda --directory /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/dropSeqPipe_mydata
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	SingleCellRnaSeqMetricsCollector
	1	create_intervals
	1	extract
	1	plot_rna_metrics
	4

[Sat Nov 17 09:21:57 2018]
localrule create_intervals:
    input: /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/genes/genes.reduced.gtf, /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.dict
    output: /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.rRNA.intervals
    jobid: 10

Activating conda environment: /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/dropSeqPipe_mydata/.snakemake/conda/59f26949
Error: Invalid or corrupt jarfile /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/drop-seq-tools-wrapper.sh
[Sat Nov 17 09:21:57 2018]
Error in rule create_intervals:
    jobid: 10
    output: /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.rRNA.intervals
    conda-env: /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/dropSeqPipe_mydata/.snakemake/conda/59f26949

RuleException:
CalledProcessError in line 73 of /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/rules/generate_meta.smk:
Command 'source activate /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/dropSeqPipe_mydata/.snakemake/conda/59f26949; set -euo pipefail;  java -Xmx70g -jar -Djava.io.tmpdir=/home/u2510/ncbi/public/sra/dropSeqPipe-0.31/temp-directory /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/drop-seq-tools-wrapper.sh -p CreateIntervalsFiles		REDUCED_GTF=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/genes/genes.reduced.gtf		SEQUENCE_DICTIONARY=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.dict		OUTPUT=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0		PREFIX=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa ' returned non-zero exit status 1.
  File "/home/u2510/ncbi/public/sra/dropSeqPipe-0.31/rules/generate_meta.smk", line 73, in __rule_create_intervals
  File "/home/u2510/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/dropSeqPipe_mydata/.snakemake/log/2018-11-17T092137.104780.snakemake.log
