### ISSUE TITLE
violin plot execution fails

### ISSUE THREAD

**Issue by cgirardot** [Hoohm/dropSeqPipe#54]
Hi, 

When the violin plot job is about to be launched, I got:
```
Traceback (most recent call last):
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/__init__.py", line 541, in snakemake
    report=report)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/workflow.py", line 653, in execute
    success = scheduler.schedule()
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/scheduler.py", line 286, in schedule
    self.run(job)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/scheduler.py", line 302, in run
    error_callback=self._error)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/executors.py", line 638, in run
    jobscript = self.get_jobscript(job)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/executors.py", line 496, in get_jobscript
    cluster=self.cluster_wildcards(job))
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/executors.py", line 556, in cluster_wildcards
    return Wildcards(fromdict=self.cluster_params(job))
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/executors.py", line 551, in cluster_params
    cluster[key] = job.format_wildcards(value)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/jobs.py", line 709, in format_wildcards
    return format(string, **_variables)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/site-packages/snakemake/utils.py", line 326, in format
    return fmt.format(_pattern, *args, **variables)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/string.py", line 191, in format
    return self.vformat(format_string, args, kwargs)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/string.py", line 195, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/string.py", line 235, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/g/funcgen/gbcs/public/software/conda/envs/snakemake-5.2.1/lib/python3.5/string.py", line 306, in get_field
    obj = getattr(obj, i)
AttributeError: 'Wildcards' object has no attribute 'sample'
```

Sorry for not doing a PR, but the quick fix is to add the following in the cluster.yaml
```
violine_plots:
    time: "00:10:00"
    output: "logs/cluster/{rule}.out"
    error: "logs/cluster/{rule}.err"
```

do you mind adding this in the repo? 

Thx

**Comment by Hoohm** [comment]
I've seen it crawl up sometimes with rules I actually don't want to run on the nodes.
I'd rather have this rule added to the localerules in the header since it's pretty low in cpu and memory usage.

**Comment by Hoohm** [comment]
This should be fixed now
