### ISSUE TITLE
I can not find the jar directory! help!!!

### ISSUE THREAD

**Issue by Jun-Lizst** [Hoohm/dropSeqPipe#62]
Error: Unable to access jarfile /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/jar/dropseq.jar

**Comment by Hoohm** [comment]
@Jun-NIBS 
You need to give more context to your issues. Just the error is not enough.

* What command did you run?
* Which step is getting this error?
* Is this on a cluster? Do you have sudo access?

**Comment by Jun-Lizst** [comment]
My another question going to be like this when I run:
snakemake --cores 8 meta --use-conda --directory /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/dropSeqPipe_mydata
Other rules it finished well. 
there remain one issue that I try many many times and cannot fix:
[Sat Nov 17 13:18:26 2018]
localrule create_intervals:
    input: /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/genes/genes.reduced.gtf, /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.dict
    output: /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.rRNA.intervals
    jobid: 3

Activating conda environment: /home/u2510/ncbi/public/sra/dropSeqPipe-0.31/dropSeqPipe_mydata/.snakemake/conda/59f26949
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/u2510/ncbi/public/sra/dropSeqPipe-0.31/temp-directory
[Sat Nov 17 13:18:27 CST 2018] org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles SEQUENCE_DICTIONARY=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.dict REDUCED_GTF=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/genes/genes.reduced.gtf OUTPUT=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0 PREFIX=/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Sat Nov 17 13:18:27 CST 2018] Executing as u2510@GenekServer-0 on Linux 4.4.0-130-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Picard version: 1.13(7bed8f4_1513008033)
[Sat Nov 17 13:18:32 CST 2018] org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=2708471808
Exception in thread "main" htsjdk.samtools.SAMException: Error opening file for writing: genome.fa.genes.intervals
	at htsjdk.samtools.util.IOUtil.openFileForWriting(IOUtil.java:589)
	at htsjdk.samtools.util.IOUtil.openFileForBufferedWriting(IOUtil.java:597)
	at htsjdk.samtools.util.IOUtil.openFileForBufferedWriting(IOUtil.java:604)
	at htsjdk.samtools.util.IntervalList.write(IntervalList.java:525)
	at org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles.write(CreateIntervalsFiles.java:215)
	at org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles.doWork(CreateIntervalsFiles.java:160)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
Caused by: java.io.FileNotFoundException: /home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/home/u2510/lj/rnaseq/10Xdata/refdata_scRNAseq/refdata-cellranger-mm10-1.2.0/fasta/genome.fa.genes.intervals (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at htsjdk.samtools.util.IOUtil.openFileForWriting(IOUtil.java:585)
	... 8 more
[Sat Nov 17 13:18:32 2018]

The file seem can not write into expected dirctory and named wrong.
Please give me some suggestion!! Thanks!

**Comment by Jun-Lizst** [comment]
@Hoohm

**Comment by Puriney** [comment]
As the author mentioned, you'd better answer the details first to give the developers more clues about what is happening.

In addition, you might reconsider a more friendly and precise title rather than 'abcdxyz, help!!!'. And be wise about using the @ feature in Github as email bombing is not a suggested way to get attention.

Good luck.
