### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by PGuen** [Hoohm/dropSeqPipe#86]
Hi,

i get the following error message in results/logs/bbmap/TC_10_repair.txt. The pipeline freezes after the `plot_adapter_content` rule.  I pushed the RAM already to 200 GB. Fastq files are quite big (~150gb). Any ideas?

```
java -ea -Xmx200g -cp /results/.snakemake/conda/3c16feaa/opt/bbmap-38.22-1/current/ jgi.SplitPairsAndSingles rp -Xmx200g in=/results/samples/TC_10/trimmmed_R1.fastq.gz in2=/results/samples/TC_10/trimmmed_R2.fastq.gz out1=/results/samples/TC_10/trimmmed_repaired_R1.fastq.gz out2=/results/samples/TC_10/trimmmed_repaired_R2.fastq.gz repair=t threads=4
Executing jgi.SplitPairsAndSingles [rp, -Xmx200g, in=/results/samples/TC_10/trimmmed_R1.fastq.gz, in2=/results/samples/TC_10/trimmmed_R2.fastq.gz, out1=/results/samples/TC_10/trimmmed_repaired_R1.fastq.gz, out2=/results/samples/TC_10/trimmmed_repaired_R2.fastq.gz, repair=t, threads=4]

Set threads to 4
Set INTERLEAVED to false
Started output stream.
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.String.substring(String.java:1969)
        at java.lang.String.subSequence(String.java:2003)
        at java.util.regex.Pattern.split(Pattern.java:1233)
        at java.lang.String.split(String.java:2380)
        at java.lang.String.split(String.java:2422)
        at jgi.SplitPairsAndSingles.repair(SplitPairsAndSingles.java:696)
        at jgi.SplitPairsAndSingles.process3_repair(SplitPairsAndSingles.java:518)
        at jgi.SplitPairsAndSingles.process2(SplitPairsAndSingles.java:284)
        at jgi.SplitPairsAndSingles.process(SplitPairsAndSingles.java:220)
        at jgi.SplitPairsAndSingles.main(SplitPairsAndSingles.java:37)
```

**Comment by Hoohm** [comment]
Hello @PGuen,

150Gb fastqs are gonna be though to deal with here. Any possibility to split them by any biological condition?

**Comment by PGuen** [comment]
Thanks for your fast response and your suggestion. Sorry, I realized that there was an issue with merging the files outside the dropseqpipe. Thanks.
